### ISSUE TITLE
Cannot sniff CAN frames using libCan

### ISSUE THREAD

**Issue by DNNlearning** [famez/J1939-Framework#5]
Is there a proper example code for how to receive and send j1939 CAN frames in C++ ? The sample C++ code that exists in CAN folder does not work, giving me errors like these: 

undefined reference to `Can::CanEasy::initialize(unsigned int, void (*)(Can::CanFrame const&, Utils::TimeStamp const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*), bool (*)())'

undefined reference to `Can::CanEasy::mSniffer'
undefined reference to `Can::CanEasy::mSniffer'
undefined reference to `Can::CanSniffer::sniff(unsigned int) const'

**Comment by famez** [comment]
For sure, 

Check out [TRCPlayer](https://github.com/famez/J1939-Framework/tree/master/BinUtils/TRCPlayer) or [TRCDumper](https://github.com/famez/J1939-Framework/tree/master/BinUtils/TRCDumper)

They make use of libCAN to inject frames from a file or record them into a file.

**Comment by famez** [comment]
Closed due to inactivity
