### ISSUE TITLE
RTS CTS Protocol

### ISSUE THREAD

**Issue by iwindsnow** [famez/J1939-Framework#6]
Thanks for giving the wonderful project. I'm learning the j1939 protocol stack and find the project lack of RTS/CTS transfer protocol. Does it support it？

**Comment by famez** [comment]
Hi,

No, it is not supported and at the moment I do not have the intention to pick up the project again, but any contribution is welcomed.

**Comment by iwindsnow** [comment]
Hi @famez 
Thanks for the feedback. I'll try to implement it.
