### ISSUE TITLE
Compile the project not success

### ISSUE THREAD

**Issue by Femtomes** [famez/J1939-Framework#7]
@famez  hi, thank you for your grate project
i want to compile the project ,but i stop in the problem of json.can you help me? 

../../J1939/libJ1939.so.1.0.0: undefined reference to `Json::Value::operator=(Json::Value&&)'
../../J1939/libJ1939.so.1.0.0: undefined reference to `Json::Value::Value(unsigned long)'
collect2: error: ld returned 1 exit status
BinUtils/j1939Decoder/CMakeFiles/j1939Decoder.dir/build.make:96: recipe for target 'BinUtils/j1939Decoder/j1939Decoder' failed

thank you

**Comment by Femtomes** [comment]
this problem solved. error in the J1939 CMakeLists.txt
# Common jsoncpp
   Common /usr/local/lib/libjsoncpp.a

**Comment by Femtomes** [comment]
have solve problem,close the issue

**Comment by nievesbrunet** [comment]
Can you give more information on how to solve this issue? Thanks!

**Comment by nievesbrunet** [comment]
I got it to work. In file _J1939-Framework/J1939/CMakeLists.txt_, change line  40.

Before: `Common jsoncpp`

Change to: `Common /usr/local/lib/libjsoncpp.a`
